### ISSUE TITLE
Add linting to CI

### ISSUE THREAD

**Issue by gangstead** [gangstead/hapi-crud-promise#4]

**Comment by chadrien** [comment]
Eslint is ran as posttest script, so travis run it. So I guess, this is done without doing anything :smile: 

![screenshot 2016-01-21 10 35 32](https://cloud.githubusercontent.com/assets/1788218/12476589/ba6322d4-c02a-11e5-8dcb-75338dd10e6c.png)

**Comment by gangstead** [comment]
Good catch @chadrien!  I made the issues and I worked on the code some more and forgot to go back and update.
